// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph_model

type ClockDrift struct {
	Timestamp      int64   `json:"timestamp"`
	Reference      string  `json:"reference"`
	LongTermDrift  float64 `json:"longTermDrift"`
	ShortTermDrift float64 `json:"shortTermDrift"`
}

type Mutation struct {
}

type NTPServer struct {
	UUID      string `json:"uuid"`
	Name      string `json:"name"`
	Address   string `json:"address"`
	Remark    string `json:"remark"`
	UpdatedAt int64  `json:"updatedAt"`
}

type Query struct {
}

type ServerOffset struct {
	Timestamp      int64  `json:"timestamp"`
	Reference      string `json:"reference"`
	Offset         int64  `json:"offset"`
	RoundTrip      int64  `json:"roundTrip"`
	RootDelay      int64  `json:"rootDelay"`
	RootDispersion int64  `json:"rootDispersion"`
	RootDistance   int64  `json:"rootDistance"`
	Stratum        int    `json:"stratum"`
	ServerRefID    string `json:"serverRefId"`
}
