package graph_resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"time"

	"github.com/bclswl0827/ntpmonitor/internal/dao/model"
	graph_model "github.com/bclswl0827/ntpmonitor/internal/server/graph_resolver/model"
	"github.com/bclswl0827/ntpmonitor/internal/settings"
	"github.com/samber/lo"
)

// SetPollingInterval is the resolver for the setPollingInterval field.
func (r *mutationResolver) SetPollingInterval(ctx context.Context, interval int64) (bool, error) {
	if err := (&settings.PollingInterval{}).Set(r.ActionHandler, interval); err != nil {
		return false, err
	}
	return true, nil
}

// SetReferenceNTPServer is the resolver for the setReferenceNTPServer field.
func (r *mutationResolver) SetReferenceNTPServer(ctx context.Context, server string) (bool, error) {
	if err := (&settings.ReferenceServer{}).Set(r.ActionHandler, server); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateObserveNTPServer is the resolver for the updateObserveNTPServer field.
func (r *mutationResolver) UpdateObserveNTPServer(ctx context.Context, uuid string, name *string, address *string, remark *string) (bool, error) {
	if err := r.ActionHandler.NtpServersUpdate(uuid, name, address, remark); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveObserveNTPServer is the resolver for the removeObserveNTPServer field.
func (r *mutationResolver) RemoveObserveNTPServer(ctx context.Context, uuid string) (bool, error) {
	if err := r.ActionHandler.NtpServersRemove(uuid); err != nil {
		return false, err
	}
	return true, nil
}

// AddObserveNTPServer is the resolver for the addObserveNTPServer field.
func (r *mutationResolver) AddObserveNTPServer(ctx context.Context, name string, address string, remark *string) (bool, error) {
	if remark == nil {
		remark = new(string)
	}
	if err := r.ActionHandler.NtpServersNew(name, address, *remark); err != nil {
		return false, err
	}
	return true, nil
}

// PurgeNTPOffsets is the resolver for the purgeNTPOffsets field.
func (r *mutationResolver) PurgeNTPOffsets(ctx context.Context, before *int64) (bool, error) {
	if before == nil {
		err := r.ActionHandler.ServerOffsetsRemoveAll()
		return err == nil, err
	}

	err := r.ActionHandler.ServerOffsetsRemoveBefore(time.UnixMilli(*before))
	return err == nil, err
}

// PurgeClockDrifts is the resolver for the purgeClockDrifts field.
func (r *mutationResolver) PurgeClockDrifts(ctx context.Context, before *int64) (bool, error) {
	if before == nil {
		err := r.ActionHandler.ClockDriftsRemoveAll()
		return err == nil, err
	}

	err := r.ActionHandler.ClockDriftsRemoveBefore(time.UnixMilli(*before))
	return err == nil, err
}

// GetCurrentTime is the resolver for the getCurrentTime field.
func (r *queryResolver) GetCurrentTime(ctx context.Context) (int64, error) {
	t, err := r.RemoteTimeFn()
	if err != nil {
		return 0, err
	}
	return t.UnixMilli(), nil
}

// GetPollingInterval is the resolver for the getPollingInterval field.
func (r *queryResolver) GetPollingInterval(ctx context.Context) (int64, error) {
	interval, err := (&settings.PollingInterval{}).Get(r.ActionHandler)
	if err != nil {
		return 0, err
	}
	return interval.(int64), nil
}

// GetReferenceNTPServer is the resolver for the getReferenceNTPServer field.
func (r *queryResolver) GetReferenceNTPServer(ctx context.Context) (string, error) {
	server, err := (&settings.ReferenceServer{}).Get(r.ActionHandler)
	if err != nil {
		return "", err
	}
	return server.(string), nil
}

// GetObserveNTPServerList is the resolver for the getObserveNTPServerList field.
func (r *queryResolver) GetObserveNTPServerList(ctx context.Context) ([]*graph_model.NTPServer, error) {
	list, err := r.ActionHandler.NtpServersList()
	if err != nil {
		return nil, err
	}
	return lo.MapToSlice(list, func(_ string, val model.NtpServers) *graph_model.NTPServer {
		return &graph_model.NTPServer{
			UUID:    val.ServerUUID,
			Address: val.Address,
			Name:    val.ServerName,
			Remark:  val.Remark,
		}
	}), nil
}

// GetClockDrift is the resolver for the getClockDrift field.
func (r *queryResolver) GetClockDrift(ctx context.Context, start int64, end *int64) ([]*graph_model.ClockDrift, error) {
	var endTime *time.Time
	if end != nil {
		endTime = new(time.Time)
		*endTime = time.UnixMilli(*end)
	}
	list, err := r.ActionHandler.ClockDriftsQuery(time.UnixMilli(start), endTime)
	if err != nil {
		return nil, err
	}
	return lo.Map(list, func(item model.ClockDrifts, _ int) *graph_model.ClockDrift {
		return &graph_model.ClockDrift{
			Timestamp:      item.Timestamp,
			LongTermDrift:  item.LongTermDrift,
			ShortTermDrift: item.ShortTermDrift,
			Reference:      item.Reference,
		}
	}), nil
}

// GetServerOffset is the resolver for the getServerOffset field.
func (r *queryResolver) GetServerOffset(ctx context.Context, uuid string, start int64, end *int64) ([]*graph_model.ServerOffset, error) {
	var endTime *time.Time
	if end != nil {
		endTime = new(time.Time)
		*endTime = time.UnixMilli(*end)
	}
	list, err := r.ActionHandler.ServerOffsetsQuery(uuid, time.UnixMilli(start), endTime)
	if err != nil {
		return nil, err
	}
	return lo.Map(list, func(item model.ServerOffsets, _ int) *graph_model.ServerOffset {
		return &graph_model.ServerOffset{
			Timestamp:      item.Timestamp,
			Reference:      item.Reference,
			Offset:         item.Offset,
			RoundTrip:      item.RoundTrip,
			RootDelay:      item.RootDelay,
			RootDispersion: item.RootDispersion,
			RootDistance:   item.RootDistance,
			Stratum:        item.Stratum,
			ServerRefID:    item.ServerRefId,
		}
	}), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
