package graph_resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"time"

	"github.com/bclswl0827/ntpmonitor/internal/dao/model"
	graph_model "github.com/bclswl0827/ntpmonitor/internal/server/graph_resolver/model"
	"github.com/bclswl0827/ntpmonitor/internal/settings"
	"github.com/samber/lo"
)

// SetFailureRetries is the resolver for the setFailureRetries field.
func (r *mutationResolver) SetFailureRetries(ctx context.Context, password string, retries int32) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := (&settings.FailureRetries{}).Set(r.ActionHandler, retries); err != nil {
		return false, err
	}
	return true, nil
}

// SetPollingInterval is the resolver for the setPollingInterval field.
func (r *mutationResolver) SetPollingInterval(ctx context.Context, password string, interval int64) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := (&settings.PollingInterval{}).Set(r.ActionHandler, interval); err != nil {
		return false, err
	}
	return true, nil
}

// SetPollingTimeout is the resolver for the setPollingTimeout field.
func (r *mutationResolver) SetPollingTimeout(ctx context.Context, password string, timeout int64) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := (&settings.PollingTimeout{}).Set(r.ActionHandler, timeout); err != nil {
		return false, err
	}
	return true, nil
}

// SetPPMWindow is the resolver for the setPPMWindow field.
func (r *mutationResolver) SetPPMWindow(ctx context.Context, password string, window int64) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := (&settings.PPMWindow{}).Set(r.ActionHandler, window); err != nil {
		return false, err
	}
	return true, nil
}

// SetRetentionDays is the resolver for the setRetentionDays field.
func (r *mutationResolver) SetRetentionDays(ctx context.Context, password string, days int64) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := (&settings.RetentionDays{}).Set(r.ActionHandler, days); err != nil {
		return false, err
	}
	return true, nil
}

// SetReferenceNTPServer is the resolver for the setReferenceNTPServer field.
func (r *mutationResolver) SetReferenceNTPServer(ctx context.Context, password string, server string) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := (&settings.ReferenceServer{}).Set(r.ActionHandler, server); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateObserveNTPServer is the resolver for the updateObserveNTPServer field.
func (r *mutationResolver) UpdateObserveNTPServer(ctx context.Context, password string, uuid string, name *string, address *string, remark *string) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := r.ActionHandler.NtpServersUpdate(uuid, name, address, remark); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveObserveNTPServer is the resolver for the removeObserveNTPServer field.
func (r *mutationResolver) RemoveObserveNTPServer(ctx context.Context, password string, uuid string) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if err := r.ActionHandler.NtpServersRemove(uuid); err != nil {
		return false, err
	}
	return true, nil
}

// AddObserveNTPServer is the resolver for the addObserveNTPServer field.
func (r *mutationResolver) AddObserveNTPServer(ctx context.Context, password string, name string, address string, remark *string) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if remark == nil {
		remark = new(string)
	}
	if err := r.ActionHandler.NtpServersNew(name, address, *remark); err != nil {
		return false, err
	}
	return true, nil
}

// PurgeNTPOffsets is the resolver for the purgeNTPOffsets field.
func (r *mutationResolver) PurgeNTPOffsets(ctx context.Context, password string, before *int64) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if before == nil {
		err := r.ActionHandler.ServerOffsetsRemoveAll()
		return err == nil, err
	}

	err := r.ActionHandler.ServerOffsetsRemoveBefore(time.UnixMilli(*before))
	return err == nil, err
}

// PurgeClockDrifts is the resolver for the purgeClockDrifts field.
func (r *mutationResolver) PurgeClockDrifts(ctx context.Context, password string, before *int64) (bool, error) {
	if !r.isValidPassword(password) {
		return false, errors.New("unauthorized access")
	}
	if before == nil {
		err := r.ActionHandler.ClockDriftsRemoveAll()
		return err == nil, err
	}

	err := r.ActionHandler.ClockDriftsRemoveBefore(time.UnixMilli(*before))
	return err == nil, err
}

// GetGlobalSettings is the resolver for the getGlobalSettings field.
func (r *queryResolver) GetGlobalSettings(ctx context.Context, password string) (*graph_model.GlobalSettings, error) {
	if !r.isValidPassword(password) {
		return nil, errors.New("unauthorized access")
	}

	retries, err := (&settings.FailureRetries{}).Get(r.ActionHandler)
	if err != nil {
		return nil, err
	}
	interval, err := (&settings.PollingInterval{}).Get(r.ActionHandler)
	if err != nil {
		return nil, err
	}
	timeout, err := (&settings.PollingTimeout{}).Get(r.ActionHandler)
	if err != nil {
		return nil, err
	}
	window, err := (&settings.PPMWindow{}).Get(r.ActionHandler)
	if err != nil {
		return nil, err
	}
	server, err := (&settings.ReferenceServer{}).Get(r.ActionHandler)
	if err != nil {
		return nil, err
	}
	retention, err := (&settings.RetentionDays{}).Get(r.ActionHandler)
	if err != nil {
		return nil, err
	}

	return &graph_model.GlobalSettings{
		FailureRetries:  retries.(int64),
		PollingInterval: interval.(int64),
		PollingTimeout:  timeout.(int64),
		PpmWindow:       window.(int64),
		ReferenceServer: server.(string),
		RetentionDays:   retention.(int64),
	}, nil
}

// VerifyPassword is the resolver for the verifyPassword field.
func (r *queryResolver) VerifyPassword(ctx context.Context, password string) (bool, error) {
	return r.isValidPassword(password), nil
}

// GetCurrentTime is the resolver for the getCurrentTime field.
func (r *queryResolver) GetCurrentTime(ctx context.Context) (*graph_model.RemoteTime, error) {
	t, s, ref, err := r.RemoteTimeFn()
	if err != nil {
		return nil, err
	}
	return &graph_model.RemoteTime{Timestamp: t.UnixMilli(), SyncedAt: s.UnixMilli(), Reference: ref}, nil
}

// GetObserveNTPServerList is the resolver for the getObserveNTPServerList field.
func (r *queryResolver) GetObserveNTPServerList(ctx context.Context) ([]*graph_model.NTPServer, error) {
	list, err := r.ActionHandler.NtpServersList()
	if err != nil {
		return nil, err
	}
	return lo.MapToSlice(list, func(_ string, val model.NtpServers) *graph_model.NTPServer {
		return &graph_model.NTPServer{
			UUID:      val.ServerUUID,
			Address:   val.Address,
			Name:      val.ServerName,
			Remark:    val.Remark,
			UpdatedAt: val.UpdatedAt,
			CreatedAt: val.CreatedAt,
		}
	}), nil
}

// GetClockDrifts is the resolver for the getClockDrifts field.
func (r *queryResolver) GetClockDrifts(ctx context.Context, start int64, end *int64) ([]*graph_model.ClockDrift, error) {
	var endTime *time.Time
	if end != nil {
		endTime = new(time.Time)
		*endTime = time.UnixMilli(*end)
	}
	list, err := r.ActionHandler.ClockDriftsQuery(time.UnixMilli(start), endTime)
	if err != nil {
		return nil, err
	}
	return lo.Map(list, func(item model.ClockDrifts, _ int) *graph_model.ClockDrift {
		return &graph_model.ClockDrift{
			Timestamp:      item.Timestamp,
			LongTermDrift:  item.LongTermDrift,
			ShortTermDrift: item.ShortTermDrift,
			Reference:      item.Reference,
		}
	}), nil
}

// GetServerOffsets is the resolver for the getServerOffsets field.
func (r *queryResolver) GetServerOffsets(ctx context.Context, uuid string, start int64, end *int64) ([]*graph_model.ServerOffset, error) {
	var endTime *time.Time
	if end != nil {
		endTime = new(time.Time)
		*endTime = time.UnixMilli(*end)
	}
	list, err := r.ActionHandler.ServerOffsetsQuery(uuid, time.UnixMilli(start), endTime)
	if err != nil {
		return nil, err
	}
	return lo.Map(list, func(item model.ServerOffsets, _ int) *graph_model.ServerOffset {
		return &graph_model.ServerOffset{
			Timestamp:      item.Timestamp,
			Reference:      item.Reference,
			Offset:         item.Offset,
			RoundTrip:      item.RoundTrip,
			RootDelay:      item.RootDelay,
			RootDispersion: item.RootDispersion,
			RootDistance:   item.RootDistance,
			Stratum:        item.Stratum,
			ServerRefID:    item.ServerRefId,
		}
	}), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
